### ISSUE TITLE
Unable to do the inference

### ISSUE THREAD

**Issue by nikhilbv** [rolandying/FusionLane#2]
Hi!! Great work. I am trying to do the inference according to the given readme. But there's an error which I'm not able to debug. 
I'm using -
* ubuntu 18.04 LTS
* Tensorflow-GPU 1.15.0
* CUDA Version 10.1
*  Nvidia GeForce 940MX GPU

Here is the traceback -
WARNING: Logging before flag parsing goes to stderr.
W0312 18:48:39.987103 140388031825728 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0312 18:48:40.096321 140388031825728 module_wrapper.py:139] From inference.py:113: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0312 18:48:40.096467 140388031825728 module_wrapper.py:139] From inference.py:113: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0312 18:48:40.096754 140388031825728 module_wrapper.py:139] From inference.py:115: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

I0312 18:48:40.097267 140388031825728 estimator.py:1800] Using default config.
I0312 18:48:40.097595 140388031825728 estimator.py:212] Using config: {'_model_dir': '/home/nikhil/Downloads/Fusionlane_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fae15674ef0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
W0312 18:48:40.098081 140388031825728 module_wrapper.py:139] From /codehub/external/FusionLane/dataset_util.py:60: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0312 18:48:40.179597 140388031825728 module_wrapper.py:139] From /codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.read_file is deprecated. Please use tf.io.read_file instead.

2020-03-12 18:48:40.355463: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-12 18:48:40.363073: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-12 18:48:40.363401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce 940MX major: 5 minor: 0 memoryClockRate(GHz): 0.8605
pciBusID: 0000:01:00.0
2020-03-12 18:48:40.363629: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-03-12 18:48:40.364462: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-03-12 18:48:40.365303: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-03-12 18:48:40.365548: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-03-12 18:48:40.366586: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-03-12 18:48:40.367439: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-03-12 18:48:40.367601: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/lib64:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server
2020-03-12 18:48:40.367611: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
W0312 18:48:40.373600 140388031825728 deprecation.py:323] From /codehub/external/FusionLane/preprocessing.py:237: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0312 18:48:40.406240 140388031825728 deprecation.py:323] From /codehub/external/FusionLane/preprocessing.py:269: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.
I0312 18:48:40.414868 140388031825728 estimator.py:1148] Calling model_fn.
W0312 18:48:40.446229 140388031825728 module_wrapper.py:139] From /codehub/external/FusionLane/xception.py:43: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0312 18:48:40.447366 140388031825728 deprecation.py:323] From /codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W0312 18:48:41.608222 140388031825728 module_wrapper.py:139] From /codehub/external/FusionLane/mymodel.py:59: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

W0312 18:48:41.638857 140388031825728 deprecation.py:323] From /codehub/external/FusionLane/mymodel.py:135: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
W0312 18:48:41.640462 140388031825728 deprecation.py:323] From /codehub/external/FusionLane/mymodel.py:141: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
W0312 18:48:41.678177 140388031825728 nn_ops.py:4283] Large dropout rate: 0.6 (>0.5). In TensorFlow 2.x, dropout() uses dropout rate instead of keep_prob. Please ensure that this is intended.
W0312 18:48:41.692203 140388031825728 deprecation.py:506] From /codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/contrib/rnn/python/ops/rnn_cell.py:2244: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0312 18:48:41.771372 140388031825728 deprecation.py:323] From /codehub/external/FusionLane/mymodel.py:193: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
[None, 321, 321, 1]
I0312 18:48:41.773088 140388031825728 estimator.py:1150] Done calling model_fn.
W0312 18:48:41.888551 140388031825728 deprecation.py:323] From /codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
I0312 18:48:42.143969 140388031825728 monitored_session.py:240] Graph was finalized.
2020-03-12 18:48:42.144254: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-12 18:48:42.165618: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2899885000 Hz
2020-03-12 18:48:42.166148: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5051790 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-12 18:48:42.166183: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-12 18:48:42.190789: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-12 18:48:42.191151: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4fe1d60 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-03-12 18:48:42.191163: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce 940MX, Compute Capability 5.0
2020-03-12 18:48:42.191349: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-12 18:48:42.191637: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce 940MX major: 5 minor: 0 memoryClockRate(GHz): 0.8605
pciBusID: 0000:01:00.0
2020-03-12 18:48:42.191712: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-03-12 18:48:42.191758: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-03-12 18:48:42.191774: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-03-12 18:48:42.191800: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-03-12 18:48:42.191811: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-03-12 18:48:42.191844: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-03-12 18:48:42.191968: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/lib64:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server
2020-03-12 18:48:42.191978: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-03-12 18:48:42.192008: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-12 18:48:42.192036: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-03-12 18:48:42.192054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
I0312 18:48:42.193250 140388031825728 saver.py:1284] Restoring parameters from /home/nikhil/Downloads/Fusionlane_model/model.ckpt-Fusionlane
I0312 18:48:42.653591 140388031825728 session_manager.py:500] Running local_init_op.
I0312 18:48:42.695646 140388031825728 session_manager.py:502] Done running local_init_op.
2020-03-12 18:48:44.958986: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at spacetobatch_op.cc:219 : Invalid argument: padded_shape[0]=40 is not divisible by block_shape[0]=6
2020-03-12 18:48:44.958986: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at spacetobatch_op.cc:219 : Invalid argument: padded_shape[0]=52 is not divisible by block_shape[0]=12
2020-03-12 18:48:44.958986: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at spacetobatch_op.cc:219 : Invalid argument: padded_shape[0]=76 is not divisible by block_shape[0]=18
Traceback (most recent call last):
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: padded_shape[0]=40 is not divisible by block_shape[0]=6
	 [[{{node aspp/conv_3x3_1/SpaceToBatchND}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 115, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "inference.py", line 87, in main
    for pred_dict, image_path in zip(predictions, image_files):
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 640, in predict
    preds_evaluated = mon_sess.run(predictions)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: padded_shape[0]=40 is not divisible by block_shape[0]=6
	 [[node aspp/conv_3x3_1/SpaceToBatchND (defined at /codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'aspp/conv_3x3_1/SpaceToBatchND':
  File "inference.py", line 115, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "inference.py", line 87, in main
    for pred_dict, image_path in zip(predictions, image_files):
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 622, in predict
    features, None, ModeKeys.PREDICT, self.config)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/codehub/external/FusionLane/mymodel.py", line 187, in network_model_fn
    logits = network(features,region, mode == tf.estimator.ModeKeys.TRAIN)
  File "/codehub/external/FusionLane/mymodel.py", line 122, in model
    encoder_output = atrous_spatial_pyramid_pooling(net, batch_norm_decay, is_training)
  File "/codehub/external/FusionLane/mymodel.py", line 48, in atrous_spatial_pyramid_pooling
    conv_3x3_1 = layers_lib.conv2d(inputs, depth, [3, 3], stride=1, rate=atrous_rates[0], scope='conv_3x3_1')
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py", line 1159, in convolution2d
    conv_dims=2)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1700, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/layers/base.py", line 548, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 854, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 234, in wrapper
    return converted_call(f, options, args, kwargs)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 439, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 330, in _call_unconverted
    return f(*args, **kwargs)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 197, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 1134, in __call__
    return self.conv_op(inp, filter)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 639, in __call__
    return self.call(inp, filter)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 622, in _with_space_to_batch_call
    input=inp, block_shape=dilation_rate, paddings=paddings)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 9652, in space_to_batch_nd
    paddings=paddings, name=name)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/codehub/virtualmachines/virtualenvs/py_3-6-9_2019-12-30/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by rolandying** [comment]
Thank you for your interest in our project. The error was caused by the testing image I uploaded with the incorrect resolution, the right testing set has already uploaded, the link is [here](https://drive.google.com/open?id=15IKQ4eVhmbV7J3Ibu1PNXgC89gMnZvQP). It should work now, if there is any other problems, please let me know.
